"""Add created_at to api_keys

Revision ID: 62e77a80cfd2
Revises: 
Create Date: 2025-09-24 23:28:45.426335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62e77a80cfd2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('api_keys', 'key_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.create_unique_constraint(None, 'api_keys', ['key_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'api_keys', type_='unique')
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.alter_column('api_keys', 'key_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('api_keys', 'created_at')
    # ### end Alembic commands ###
